baseURL = 'https://hugosite-ezt.pages.dev/'
languageCode = 'ja-jp'
theme = "moemoe"
title = '萌え萌えカンパニー'

[params]
[[params.menu]]
identifier = 'company'
title = 'Company'
url = ''

[[params.menu]]
identifier = 'news'
title = 'News'
url = ''

[[params.menu]]
identifier = 'works'
title = 'Works'
url = '/works/'

[[params.menu]]
identifier = 'staff'
title = 'Staff'
url = '/staff/'

[[params.menu]]
identifier = 'contact'
title = 'Contact'
url = ''

[[params.staffs]]
description = "創設者兼チーフ平社員オフィサー"
icon = "/img/staff/davide.jpg"
name = "だびで（オタク）"
role = "CHO"
twitter = "https://twitter.com/Vern_rvSaki"
website = "https://rnvneko.info/"

[[params.staffs]]
description = "チーフツンデレオフィサー"
icon = "/img/staff/phone.png"
name = "p-hone（オタク）"
role = "CTO"
twitter = "https://twitter.com/p__hone"
website = "https://p-hone.info/"

[[params.staffs]]
description = "チーフ不良オフィサー"
icon = "/img/staff/sakura.jpg"
name = "佐倉（オタク）"
role = "CFO"
twitter = "https://twitter.com/sakusakuunagi"
website = "https://sakusakuunagi.hatenadiary.jp/"

[[params.staffs]]
description = "チーフ先生オフィサー"
icon = "/img/staff/no_image.png"
name = "nemu"
role = "CSO"
twitter = ""
website = ""

[[params.staffs]]
description = "チーフエロゲオフィサー"
icon = "/img/staff/subaru.jpg"
name = "すばる（オタク）"
role = "CEO"
twitter = "https://twitter.com/MUR_SBR"
website = ""

[[params.staffs]]
description = "チーフDJオフィサー"
icon = "/img/staff/line.png"
name = "ライン（オタク）"
role = "CDO"
twitter = "https://twitter.com/parudo63"
website = "https://note.com/parudo63/"

[[params.staffs]]
description = "チーフライターオフィサー"
icon = "/img/staff/highland.png"
name = "highland（オタク）"
role = "CWO"
twitter = "https://twitter.com/highland_sh"
website = "https://highland.hatenablog.com/"

[[params.staffs]]
description = "チーフ百合オフィサー"
icon = "/img/staff/ukitouchtypist.png"
name = "園田うき（オタク）"
role = "CYO"
twitter = "https://twitter.com/ukitouchtypist"
website = "http://www.ukitouchtypist.org/"

[[params.staffs]]
description = ""
icon = "/img/staff/no_image.png"
name = "ぽえむ"
role = ""
twitter = "https://twitter.com/Z04Tk"
website = ""

[[params.staffs]]
description = ""
icon = "/img/staff/no_image.png"
name = "チコビクトリー"
role = ""
twitter = "https://twitter.com/DBLFACE"
website = ""

[[params.staffs]]
description = ""
icon = "/img/staff/no_image.png"
name = "ウニニニニードル"
role = ""
twitter = "https://twitter.com/unininini_doru"
website = ""

[[params.staffs]]
description = ""
icon = "/img/staff/no_image.png"
name = "wind"
role = ""
twitter = "https://twitter.com/wind_0180"
website = ""

[[params.works]]
author = ""
date = "2022/12/31"
description = "既刊の『ゼロから始めるお絵描きの書』ではページ数の関係で取り扱えなかった内容や補足的な内容を収録したフルカラー52ページのボリューム満点の一冊です。"
image = "/img/works/zeroe02.jpg"
name = "ゼロから始めるお絵描きの書＋"
url = "https://moemoecompany.booth.pm/items/4483008"

[[params.works]]
author = ""
date = "2022/08/13"
description = "コロナ禍で時間を持て余したお絵描き初心者がDiscordを通じて画力を向上させていった記録を一冊の本にまとめました。"
image = "/img/works/zeroe01.png"
name = "ゼロから始めるお絵描きの書"
url = "https://moemoecompany.booth.pm/items/4084008"

[[params.works]]
author = "highland, p-hone, だびで"
date = "2022/03/19"
description = ""
image = "/img/works/dochilove05_ura.jpg"
name = "アニソンクラブイベント『どちラブ! Vol.5』フライヤー（裏）"
url = "https://twipla.jp/events/503177"

[[params.works]]
author = "ライン, nemu, 佐倉"
date = "2022/03/19"
description = ""
image = "/img/works/dochilove05.jpg"
name = "アニソンクラブイベント『どちラブ! Vol.5』フライヤー"
url = "https://twipla.jp/events/503177"

[[params.works]]
author = "p-hone, ライン, すばる"
date = "2021/11/06"
description = ""
image = "/img/works/dochilove04.jpg"
name = "アニソンクラブイベント『どちラブ! Vol.4』フライヤー"
url = "https://twipla.jp/events/492089"

[[params.works]]
author = "p-hone, 佐倉, すばる"
date = "2021/07/10"
description = ""
image = "/img/works/dochilove_spinoff.png"
name = "アニソンクラブイベント『どちラブ! スピンオフ』フライヤー"
url = "https://twipla.jp/events/454410"

[[params.works]]
author = "ライン, 佐倉, すばる"
date = "2021/02/23"
description = ""
image = "/img/works/dochilove03.jpg"
name = "アニソンクラブイベント『どちラブ! Vol.3』フライヤー"
url = "https://twipla.jp/events/470591"

[[params.works]]
author = "だびで, p-hone"
date = "2021/01/16"
description = ""
image = "/img/works/anipod02.jpg"
name = "アニソンクラブイベント『アニPod こうりゅうせん!』フライヤー"
url = "https://twitter.com/AniPoD_official/status/1350386794387234816"

[[params.works]]
author = "佐倉, すばる, p-hone"
date = "2020/11/21"
description = ""
image = "/img/works/dochilove02.jpg"
name = "アニソンクラブイベント『どちラブ! Vol.2』フライヤー"
url = "https://twipla.jp/events/454410"

[[params.works]]
author = "だびで, p-hone"
date = "2020/09/05"
description = ""
image = "/img/works/anipod01.jpg"
name = "アニソンクラブイベント『アニPod』フライヤー"
url = "https://twipla.jp/events/470591"

[[params.works]]
author = "佐倉, p-hone, だびで"
date = "2020/08/22"
description = ""
image = "/img/works/dochilove01.jpg"
name = "アニソンクラブイベント『どちラブ! Vol.1』フライヤー"
url = "https://twipla.jp/events/454410"
