baseURL = 'https://hugosite-ezt.pages.dev/'
languageCode = 'ja-jp'
theme = "moemoe"
title = '萌え萌えカンパニー'

[menu]
[[menu.main]]
identifier = 'company'
title = 'Company'
url = ''
order = 0

[[menu.main]]
identifier = 'news'
title = 'News'
url = ''
order = 1

[[menu.main]]
identifier = 'works'
title = 'Works'
url = '/works/'
order = 2

[[menu.main]]
identifier = 'staff'
title = 'Staff'
url = '/staff/'
order = 3

[[menu.main]]
identifier = 'contact'
title = 'Contact'
url = ''
order = 4

[params]
[[params.staffs]]
name = "だびで（オタク）"
icon = "/img/davide.jpg"
twitter = "https://twitter.com/Vern_rvSaki"
website = "https://rnvneko.info/"
role = "CHO"
description = "創設者兼チーフ平社員オフィサー"

[[params.staffs]]
name = "p-hone（オタク）"
icon = "/img/phone.png"
twitter = "https://twitter.com/p__hone"
website = "https://p-hone.info/"
role = "CTO"
description = "チーフツンデレオフィサー"

[[params.staffs]]
name = "佐倉（オタク）"
icon = "/img/sakura.jpg"
twitter = "https://twitter.com/sakusakuunagi"
website = "https://sakusakuunagi.hatenadiary.jp/"
role = "CFO"
description = "チーフ不良オフィサー"

[[params.staffs]]
name = "nemu"
icon = "/img/no_image.png"
twitter = ""
website = ""
role = "CSO"
description = "チーフ先生オフィサー"

[[params.staffs]]
name = "すばる（オタク）"
icon = "/img/subaru.jpg"
twitter = "https://twitter.com/MUR_SBR"
website = ""
role = "CEO"
description = "チーフエロゲオフィサー"

[[params.staffs]]
name = "ライン（オタク）"
icon = "/img/line.png"
twitter = "https://twitter.com/parudo63"
website = "https://note.com/parudo63/"
role = "CDO"
description = "チーフDJオフィサー"

[[params.staffs]]
name = "highland（オタク）"
icon = "/img/highland.png"
twitter = "https://twitter.com/highland_sh"
website = "https://highland.hatenablog.com/"
role = "CWO"
description = "チーフライターオフィサー"

[[params.staffs]]
name = "園田うき"
icon = "/img/ukitouchtypist.png"
twitter = "https://twitter.com/ukitouchtypist"
website = "http://www.ukitouchtypist.org/"
role = ""
description = ""

[[params.staffs]]
name = "ぽえむ"
icon = "/img/no_image.png"
twitter = "https://twitter.com/Z04Tk"
website = ""
role = ""
description = ""

[[params.staffs]]
name = "チコビクトリー"
icon = "/img/no_image.png"
twitter = "https://twitter.com/DBLFACE"
website = ""
role = ""
description = ""

[[params.staffs]]
name = "ウニニニニードル"
icon = "/img/no_image.png"
twitter = "https://twitter.com/unininini_doru"
website = ""
role = ""
description = ""

[[params.staffs]]
name = "wind"
icon = "/img/no_image.png"
twitter = "https://twitter.com/wind_0180"
website = ""
role = ""
description = ""

[[params.works]]
name = "ゼロから始めるお絵描きの書"
url = "https://moemoecompany.booth.pm/items/4084008"
date = "2022/08/13"
author = ""
image = "/img/zeroe01.png"
description = "コロナ禍で時間を持て余したお絵描き初心者がDiscordを通じて画力を向上させていった記録を一冊の本にまとめました。"
