baseURL = 'https://hugosite-ezt.pages.dev/'
languageCode = 'ja-jp'
theme = "moemoe"
title = '萌え萌えカンパニー'

[params]
[[params.menu]]
identifier = 'company'
title = 'Company'
url = ''

[[params.menu]]
identifier = 'news'
title = 'News'
url = ''

[[params.menu]]
identifier = 'works'
title = 'Works'
url = '/works/'

[[params.menu]]
identifier = 'staff'
title = 'Staff'
url = '/staff/'

[[params.menu]]
identifier = 'contact'
title = 'Contact'
url = ''

[[params.staffs]]
description = "創設者兼チーフ平社員オフィサー"
icon = "/img/davide.jpg"
name = "だびで（オタク）"
role = "CHO"
twitter = "https://twitter.com/Vern_rvSaki"
website = "https://rnvneko.info/"

[[params.staffs]]
description = "チーフツンデレオフィサー"
icon = "/img/phone.png"
name = "p-hone（オタク）"
role = "CTO"
twitter = "https://twitter.com/p__hone"
website = "https://p-hone.info/"

[[params.staffs]]
description = "チーフ不良オフィサー"
icon = "/img/sakura.jpg"
name = "佐倉（オタク）"
role = "CFO"
twitter = "https://twitter.com/sakusakuunagi"
website = "https://sakusakuunagi.hatenadiary.jp/"

[[params.staffs]]
description = "チーフ先生オフィサー"
icon = "/img/no_image.png"
name = "nemu"
role = "CSO"
twitter = ""
website = ""

[[params.staffs]]
description = "チーフエロゲオフィサー"
icon = "/img/subaru.jpg"
name = "すばる（オタク）"
role = "CEO"
twitter = "https://twitter.com/MUR_SBR"
website = ""

[[params.staffs]]
description = "チーフDJオフィサー"
icon = "/img/line.png"
name = "ライン（オタク）"
role = "CDO"
twitter = "https://twitter.com/parudo63"
website = "https://note.com/parudo63/"

[[params.staffs]]
description = "チーフライターオフィサー"
icon = "/img/highland.png"
name = "highland（オタク）"
role = "CWO"
twitter = "https://twitter.com/highland_sh"
website = "https://highland.hatenablog.com/"

[[params.staffs]]
description = ""
icon = "/img/ukitouchtypist.png"
name = "園田うき"
role = ""
twitter = "https://twitter.com/ukitouchtypist"
website = "http://www.ukitouchtypist.org/"

[[params.staffs]]
description = ""
icon = "/img/no_image.png"
name = "ぽえむ"
role = ""
twitter = "https://twitter.com/Z04Tk"
website = ""

[[params.staffs]]
description = ""
icon = "/img/no_image.png"
name = "チコビクトリー"
role = ""
twitter = "https://twitter.com/DBLFACE"
website = ""

[[params.staffs]]
description = ""
icon = "/img/no_image.png"
name = "ウニニニニードル"
role = ""
twitter = "https://twitter.com/unininini_doru"
website = ""

[[params.staffs]]
description = ""
icon = "/img/no_image.png"
name = "wind"
role = ""
twitter = "https://twitter.com/wind_0180"
website = ""

[[params.works]]
author = ""
date = "2022/08/13"
description = "コロナ禍で時間を持て余したお絵描き初心者がDiscordを通じて画力を向上させていった記録を一冊の本にまとめました。"
image = "/img/zeroe01.png"
name = "ゼロから始めるお絵描きの書"
url = "https://moemoecompany.booth.pm/items/4084008"
